-- V-Talk Supabase schema
-- Run this in Supabase Dashboard > SQL Editor.
--
-- The FastAPI backend also calls SQLAlchemy Base.metadata.create_all() on startup,
-- but this script lets you prepare the database explicitly before deploying to Render.

create table if not exists public.users (
    id integer generated by default as identity primary key,
    email varchar(255) not null unique,
    full_name varchar(255) not null,
    hashed_password varchar(255) not null,
    is_active boolean not null default true,
    created_at timestamp with time zone not null default now()
);

create table if not exists public.translation_logs (
    id integer generated by default as identity primary key,
    user_id integer null references public.users(id),
    source_type varchar(32) not null,
    predicted_text varchar(16) not null,
    confidence double precision not null,
    inference_provider varchar(32) not null,
    request_id varchar(64) not null unique,
    frame_size integer not null,
    raw_payload_preview text not null,
    created_at timestamp with time zone not null default now(),
    constraint translation_logs_source_type_check
        check (source_type in ('image', 'video_frame')),
    constraint translation_logs_confidence_check
        check (confidence >= 0 and confidence <= 1),
    constraint translation_logs_frame_size_check
        check (frame_size >= 0)
);

create table if not exists public.feedback (
    id integer generated by default as identity primary key,
    translation_id integer not null references public.translation_logs(id),
    user_id integer null references public.users(id),
    rating varchar(16) not null,
    note text not null default '',
    created_at timestamp with time zone not null default now(),
    constraint feedback_rating_check
        check (rating in ('correct', 'incorrect', 'uncertain'))
);

create index if not exists ix_users_id
    on public.users(id);

create index if not exists ix_users_email
    on public.users(email);

create index if not exists ix_translation_logs_id
    on public.translation_logs(id);

create index if not exists ix_translation_logs_request_id
    on public.translation_logs(request_id);

create index if not exists ix_translation_logs_user_id_created_at
    on public.translation_logs(user_id, created_at desc);

create index if not exists ix_feedback_id
    on public.feedback(id);

create index if not exists ix_feedback_translation_id
    on public.feedback(translation_id);

create index if not exists ix_feedback_user_id
    on public.feedback(user_id);

-- Keep Row Level Security disabled for these backend-owned tables unless you
-- later access them directly from Supabase client SDK in the browser.
-- The current FastAPI backend enforces access rules itself.
alter table public.users disable row level security;
alter table public.translation_logs disable row level security;
alter table public.feedback disable row level security;
